version: "3"

services:

  ckan-dev:
    build:
      context: ckan/
      dockerfile: Dockerfile.dev
      args:
        - TZ=${TZ}
    env_file:
      - .env
    ports:
      - "0.0.0.0:${CKAN_PORT}:5000"
    volumes:
      - ./src:/srv/app/src_extensions
      - ckan_storage:/var/lib/ckan
    networks:
      main:
        aliases:
          - ckan
          - ckan-dev

  ckan-worker-dev:
    container_name: ckan-worker-dev
    command: [/srv/app/start_ckan.sh]
    build:
      context: ckan/
      dockerfile: Dockerfile.dev
      args:
        - TZ=${TZ}
    env_file:
      - .env
    volumes:
      - ./src:/srv/app/src_extensions
      - ckan_storage:/var/lib/ckan
    networks:
      main:
        aliases:
          - ckan-worker

  db:
    container_name: db
    env_file:
      - .env
    build:
      context: postgresql/
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      main:
        aliases:
          - db
          - database

  solr:
    container_name: solr
    build:
      context: solr/
    volumes:
      - solr_data:/opt/solr/server/solr/ckan/data/index
    ports:
      - "8983:8983"
    networks:
      main:
        aliases:
          - solr
    ports:
      - "8983:8983"

  redis:
    container_name: redis
    image: redis:alpine
    networks:
      main:
        aliases:
          - redis
 

volumes:
  ckan_storage:
  pg_data:
  solr_data:

networks:
  main:
